apiVersion: cache.halter.io/v1alpha1
kind: ValkeyCluster
metadata:
  labels:
    app.kubernetes.io/name: valkey-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: valkeycluster-sample
spec:
  image: valkey-server:latest
  shards: 1
  replicas: 1
  minReadySeconds: 10
  resources:
    limits:
      cpu: "0.4"
      memory: 314Mi
    requests:
      cpu: "0.2"
      memory: 214Mi
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: standard
  initialDelaySeconds: 5
