name: publish-branch

permissions: write-all

on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: publish-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: "latest"
          module: ./
          args: publish-docker --gh-token=env://GITHUB_TOKEN --tag=branch-${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
